application: s3309665
version: 3
runtime: python27
api_version: 1
threadsafe: true
libraries:
- name: jinja2
  version: latest
handlers:
- url: /images
  static_dir: images
- url: /html
  static_dir: html
- url: /.*
  script: helloworld.application
